version: "3.8"

services:
  db:
    image: postgres:16
    container_name: db
    environment:
      restart : unless-stopped
      TZ: Asia/Seoul
      POSTGRES_DB: phone_db
      POSTGRES_USER: phone_user
      POSTGRES_PASSWORD: /run/secrets/db_password
      secrets:
      - db_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U phone_user -d phone_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  spring-app:
    image: hod284/phoneapp:latest    # 여기에 네 스프링 Dockerfile 있음
    container_name: spring-phoneapp
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: Asia/Seoul
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/phone_db
      SPRING_DATASOURCE_USERNAME: phone_user
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    command: >
      sh -lc 'export SPRING_DATASOURCE_PASSWORD="$$(cat /run/secrets/db_password)";
              exec java -jar /app/phone.jar'
    secrets:
      - db_password
    ports:
      - "9081:9081"
secrets:
  db_password:
    file: .db_password.txt
volumes:
  db_data: